#!/usr/bin/env node
// Usage: node scripts/evolution-map.js [--write | --check]
//
// Renders the evolution graph in every sprites/packs/*/pack.json as mermaid
// and keeps docs/evolution-routes.md's map section in sync with it.
//
//   (no flag)  print the map to stdout
//   --write    replace the block between the markers in the doc
//   --check    exit 1 if the doc's block is stale (what the test uses)
//
// Generated rather than hand-drawn on purpose: the map's whole value is being
// true, and a hand-drawn one goes stale the first time a node is added. The
// --check mode is what makes "stale" a test failure instead of a surprise.
//
// Whether a node is drawn as live or excluded comes from readTree(), i.e. the
// same pruning the daily draw uses -- so the map shows what the rotation can
// actually reach on THIS machine, dots and all, not just what pack.json names.

const fs = require('fs');
const path = require('path');

const {
  defaultPacksDir,
  defaultSharedDir,
  listValidPacks,
  listRotationPacks,
  packTopStage,
  readTree,
  minCeilingId,
  topStageId
} = require('../lib/daily');
const { TREE } = require('../lib/evolve');

const BEGIN = '<!-- BEGIN evolution-map (generated by scripts/evolution-map.js -- do not edit by hand) -->';
const END = '<!-- END evolution-map -->';
const DOC = path.join(__dirname, '..', 'docs', 'evolution-routes.md');
const STAGES = TREE.stages.map((s) => s.id);

// digitama and baby are a single linear pair in every pack, so drawing them
// would add two nodes per diagram and no information. Said out loud in the
// caption so the map isn't quietly incomplete.
const FROM = 'child';

function safeId(pack, nodeId) {
  return `${pack}_${nodeId}`.replace(/[^A-Za-z0-9_]/g, '_');
}

function packSection(pack, packsDir, sharedDir, inRotation) {
  const raw = JSON.parse(fs.readFileSync(path.join(packsDir, pack, 'pack.json'), 'utf8'));
  const ceiling = packTopStage(packsDir, pack);
  const stages = STAGES.slice(STAGES.indexOf(FROM), STAGES.indexOf(ceiling) + 1);
  const label = raw.name || pack;
  const head = `**${label}** (\`${pack}\`) — 천장 \`${ceiling}\`` +
    (inRotation ? '' : ' · 로테이션 제외');

  if (!raw.tree) {
    const line = stages
      .map((s) => (raw.stageNames || {})[s])
      .filter(Boolean)
      .join(' → ');
    return `${head} · 트리 없음(\`stageNames\` 고정선)\n\n\`\`\`\n${line}\n\`\`\``;
  }

  const pruned = readTree(packsDir, pack, sharedDir) || {};
  const live = new Set();
  for (const s of STAGES) for (const n of pruned[s] || []) live.add(n.id);

  const lines = ['flowchart LR'];
  const excluded = [];
  for (const stage of stages) {
    for (const node of raw.tree[stage] || []) {
      const traits = Array.isArray(node.traits) && node.traits.length
        ? `<br/><i>${node.traits.join(', ')}</i>`
        : '';
      lines.push(`  ${safeId(pack, node.id)}["${node.name}${traits}"]`);
      if (!live.has(node.id)) excluded.push(safeId(pack, node.id));
    }
  }
  for (const stage of stages) {
    for (const node of raw.tree[stage] || []) {
      for (const next of node.next || []) {
        lines.push(`  ${safeId(pack, node.id)} --> ${safeId(pack, next)}`);
      }
      // A node that stops *below the minimum ceiling* is a dead end -- where
      // the old spine-return used to invent an edge. Stopping at or past it is
      // a legitimate short line, not a dead end, so it gets no marker.
      if ((node.next || []).length === 0 && STAGES.indexOf(stage) < STAGES.indexOf(minCeilingId())) {
        const stop = `${safeId(pack, node.id)}_stop`;
        lines.push(`  ${stop}(("∅"))`);
        lines.push(`  ${safeId(pack, node.id)} --> ${stop}`);
        excluded.push(stop);
      }
    }
  }
  if (excluded.length > 0) {
    lines.push('  classDef out stroke-dasharray:4 3,stroke:#999,color:#999');
    lines.push(`  class ${excluded.join(',')} out`);
  }
  return `${head}\n\n\`\`\`mermaid\n${lines.join('\n')}\n\`\`\``;
}

function render() {
  const packsDir = defaultPacksDir();
  const sharedDir = defaultSharedDir();
  const rotation = new Set(listRotationPacks(packsDir, sharedDir));
  const packs = listValidPacks(packsDir, sharedDir);
  const out = [
    `알(\`digitama\`)과 유년기(\`baby\`)는 어느 팩에서도 분기가 없어 생략했다. 성장기부터 팩의`,
    `천장까지 그린다. 점선/회색은 R2가 추첨에서 제외한 노드이며, \`∅\`는 후속이 없어 천장까지`,
    `이어지지 않는 막다른 분기다 — 예전에 spine 복귀가 가짜 엣지를 만들던 자리다.`,
    `궁극체에서 끝나는 루트는 정상이다(초궁극체가 없는 라인은 2M을 넘겨도 더 진화하지 않는다).`,
    `기울임체는 그 분기를 끌어당기는 \`trait\`(§5)이다.`,
    '',
    `최상위 스테이지는 \`${topStageId()}\`, 루트가 끝날 수 있는 최소 단계는 \`${minCeilingId()}\`. `+
    `로테이션 ${rotation.size}팩 / 유효 ${packs.length}팩.`,
    ''
  ];
  for (const pack of packs) {
    out.push(packSection(pack, packsDir, sharedDir, rotation.has(pack)), '');
  }
  return out.join('\n').replace(/\n+$/, '\n');
}

function splice(doc, body) {
  const i = doc.indexOf(BEGIN);
  const j = doc.indexOf(END);
  if (i < 0 || j < 0) {
    throw new Error(`markers not found in ${DOC} -- add ${BEGIN} / ${END}`);
  }
  return doc.slice(0, i) + BEGIN + '\n\n' + body + '\n' + doc.slice(j);
}

const mode = process.argv[2];
if (mode === '--write') {
  fs.writeFileSync(DOC, splice(fs.readFileSync(DOC, 'utf8'), render()));
  console.log(`updated the map block in ${path.relative(process.cwd(), DOC)}`);
} else if (mode === '--check') {
  const doc = fs.readFileSync(DOC, 'utf8');
  if (doc !== splice(doc, render())) {
    console.error('docs/evolution-routes.md map is stale -- run: node scripts/evolution-map.js --write');
    process.exit(1);
  }
  console.log('map is current');
} else {
  process.stdout.write(render());
}

module.exports = { render, splice, BEGIN, END, DOC };
